### ISSUE TITLE
je suis perdu dans l'installation

### ISSUE THREAD

**Issue by titof2375** [dathosim/Pronote2Homeassistant#10]
bonjour je suis un peut perdu dans l'installation de votre script.

**Comment by titof2375** [comment]
j'ai fait ca deja 
![pronote](https://user-images.githubusercontent.com/31250165/159677030-3ded5651-0fc3-4d8a-bcb3-99b69099e111.PNG)

**Comment by titof2375** [comment]
c'est apres que ca bloque

**Comment by dathosim** [comment]
Apparemment d'après ton dernier ticket tu es allé plus loin dans l'installation ? 
Je peux donc fermer ce ticket n'est-ce pas ?

**Comment by titof2375** [comment]
Ouu
