### ISSUE TITLE
Bug absence (parenthèse) avec la dernière version de pronotepy

### ISSUE THREAD

**Issue by titof2375** [dathosim/Pronote2Homeassistant#11]
bonjour, j'ai mi ta derniere version de pronote.py et je me retrouve avec cette erreur
![pepepep](https://user-images.githubusercontent.com/31250165/160671579-e46f9064-c20a-4d8e-9b77-14b6fb42ef4a.PNG)

**Comment by dathosim** [comment]
Est-ce avec un compte parent ou élève que tu te connectes ?
Aussi, sur l'interface de pronote en direct pour le compte élève, est-ce que tu peux voir des absences ou le module n'est pas présent ?
En attendant, essaye de commenter toute la partie absence pour voir si le reste passe

**Comment by titof2375** [comment]
![Screenshot_20220330-090822](https://user-images.githubusercontent.com/31250165/160772494-b89fca6f-20ed-4a19-8c75-88e507936582.png)
Je me connecte avec le compte élève.

**Comment by dathosim** [comment]
Non, il s'agit des absences de l'élève dans le menu vie scolaire / récapitulatif je crois 

Ce que tu montre c'est l'emeploi du temps - a priori le script pour la récupération de l'edt fonctionne 

Peux tu aller dans le menu vie scolaire et récapitulatif stp ?

**Comment by titof2375** [comment]
![Screenshot_20220330-092126](https://user-images.githubusercontent.com/31250165/160774682-dff2c78f-979e-48a2-8c9a-48c607a7c55d.png)
Ca

**Comment by dathosim** [comment]
Ah ? ok...ça veut dire que y'a bien des absences dans Pronote. : donc le problème vient d'ailleurs
Tu es sur que tu te connectes avec compte eleve dans le script ? 
est-ce que la variable type_compte = "eleve" ?

**Comment by titof2375** [comment]
![eleve](https://user-images.githubusercontent.com/31250165/160861311-b49f53e8-f295-4f13-9b1c-2dc5d52118b9.PNG)
la ou on rentre les identifiants et en dessous je vois ca 
![c'est pas la chose](https://user-images.githubusercontent.com/31250165/160861417-94647087-bc6c-4d06-a00f-023b563922b6.PNG)

**Comment by titof2375** [comment]
je me suis connecter avec mon compte parent est voila ce que j'ai
![hahahahatututu](https://user-images.githubusercontent.com/31250165/160862547-0e4077ac-0776-4e94-8709-3e0c5ea7c2ba.PNG)

**Comment by dathosim** [comment]
Alors l'erreur avec la connexion avec le compte parent elle me parait claire : il faut que tu initialise la variable : eleve_nom_prenom avec le nom en majuscule de ton enfant suivi du prénom en minuscule 

Exemple : 
eleve_nom_prenom = "DUPONT Amandine"

Tél qu'il apparaît sur pronote mais sans la classe entre parenthèse

Par contre je ne vois pas pourquoi avec le compte élève ça plante sur les absences...
Commente le bout de code pour voir

**Comment by titof2375** [comment]
a tu teamviewer?

**Comment by titof2375** [comment]
et a tu discord ou telegram?

**Comment by titof2375** [comment]
![plokij_LI](https://user-images.githubusercontent.com/31250165/160895339-7b877d7f-d1f9-42f2-b140-05cf91ea7755.jpg)
J'ai fait comme tu ma dis pour le nom de l'eleve "DUPONT ecric" et voila l'erreur

**Comment by dathosim** [comment]
Id discord : Dathosim#2185

**Comment by dathosim** [comment]
Ce que je vois c'est qu'il ne reconnaît pas le nom prénom de l'enfant 
A voir s'il faut mettre les accents ou pas...
Il faut tester plusieurs trucs

**Comment by titof2375** [comment]
demande faite sur dicord

![gjgjgjgjg](https://user-images.githubusercontent.com/31250165/160897575-9b1b151c-9def-4d3f-97ee-e5a88fb9bb25.PNG)
 il manque un accent, parcontre je me retrouve comme au debut

**Comment by jimsaye** [comment]
Traceback (most recent call last):
  File "pronote.py", line 208, in <module>
    absences = client.current_period.absences()
TypeError: 'list' object is not callable

idem chez moi par contre si je commente toutes les lignes absence tout est cela fonctionne.

**Comment by titof2375** [comment]
Comme chez moi

**Comment by dathosim** [comment]
Sur une autre issue, un utilisateur a corrigé le problème en supprimer les () à la fin de la ligne currentperiod.absence

Pouvez-vous essayer ?

Nb : ça doit être du à une version différente de pronotepy (la lib)

De mon côté je vais mettre à jour la lib pour voir

**Comment by jimsaye** [comment]
niquel j'ai bien les absences merci.

**Comment by titof2375** [comment]
![salutaufd](https://user-images.githubusercontent.com/31250165/161237755-e71a4608-a58f-4750-beb1-45d9ecc35775.PNG)
salut moi j'ai ca maintenant

**Comment by titof2375** [comment]
c'est moi aussi ca fonctionne merci

**Comment by sosordinet** [comment]
Effectivement dans le Pull requests c'était pour la version 2.2.0 de pronotepy. Dans la nouvelle version 2.4.0, les absences ont été changé en class, donc plus de parenthèses.

**Comment by dathosim** [comment]
corrigé ! les absences remontent bien dans la dernière version du script
