### ISSUE TITLE
note avec couleurs et non chiffre

### ISSUE THREAD

**Issue by jimsaye** [dathosim/Pronote2Homeassistant#12]
Bonjour,
les notes de mon fils en 6eme sont avec des couleurs rouge , jaune, vert et vert+
pensez vous qu'il y a une moyen de les récupérer

**Comment by dathosim** [comment]
Oui je pense !
Je crois avoir vu un des enfants du compte de demo qui est noté comme ça - il faut je regarde...
Mais si vous avez installé le module, pouvez-vous transmettre le morceau de json généré pour voir comment il est fait

**Comment by jimsaye** [comment]
je n'ai rien du tout à ce niveau, 
    "note": [],

**Comment by dathosim** [comment]
je viens de voir sur le site de démonstration de Pronote que les couleurs ne sont pas dans "note" mais dans "compètences > Evaluations" 
Cf. https://demo.index-education.net/pronote/parent.html
- Les notes : menu "Notes" puis "Les notes" 
- Les évaluations : menu "Compétences" puis "les évaluations" 
!! sélectionner l'enfant Manon en 6eme dans le site de démo

Pourriez-vous vérifier si les "notes sous formes de couleurs" de votre fils dans son Pronote sont dans Evaluations ? 
ou dans le menu notes ?
<img width="937" alt="pronote" src="https://user-images.githubusercontent.com/47037724/161297944-d886c81f-0cca-462e-a53c-d05b59362b8b.png">

**Comment by jimsaye** [comment]
oui c'est bien cela , elles sont dans menu "Compétences" puis "les évaluations"

**Comment by dathosim** [comment]
J'ai vu que les évaluations existent dans la lib pronotepy 
Donc ça doit être faisable...
Je regarde ça dès que j'ai un moment - mais n'hésitez pas à essayer 😜

**Comment by jimsaye** [comment]
Je n'y connais rien en python j'ai tenté qq chose.
en prenant exemple sur les notes 
j'arrive à récupérer une partie mais pas les évaluations.
voila ce que j'ai mis 

#Récupération des evaluations
    evaluations = client.current_period.evaluations
    evaluations = sorted(evaluations, key=lambda evaluation: evaluation.date)

    #Transformation des evaluations en Json
    jsondata['evaluation'] = []
    for evaluation in evaluations:
        jsondata['evaluation'].append({
            'date': evaluation.date.strftime("%d/%m/%Y"),
            'date_courte': evaluation.date.strftime("%d/%m"),            
            'cours': evaluation.subject.name,
            'evaluations': evaluation.description,            
            'coeff': evaluation.coefficient,

**Comment by jimsaye** [comment]
et voila ce que je récupère dans le json

"evaluation": [
        {
            "date": "12/11/2021",
            "date_courte": "19/01",
            "cours": "ARTS PLASTIQUES",
            "evaluations": "Arts plastiques \u00e9valuation T2",
            "coeff": "1"
        },
        {
            "date": "12/11/2021",
            "date_courte": "19/01",
            "cours": "TECHNOLOGIE",
            "evaluations": "Techno - T2 - A - Par matiere",
            "coeff": "1"
        },
        {
            "date": "12/11/2021",
            "date_courte": "19/01",
            "cours": "SCIENCES DE LA VIE ET DE LA TERRE",
            "evaluations": "SVT - T2 - B - Par matiere",
            "coeff": "1"
        },
        {
            "date": "12/11/2021",
            "date_courte": "19/01",
            "cours": "SCIENCES DE LA VIE ET DE LA TERRE",
            "evaluations": "SVT - T2 - A - Par matiere",
            "coeff": "1"
        },

**Comment by jimsaye** [comment]
c'est la partie acquisition que je n'arrive pas à récupérer

Contains acquisition info for an evaluation.

Attributes:	
order:int
Telling the order in which the acquisition is. The list of acquisitions is already sorted by this.

level:str
the level achieved for this acquisition

id:int
id, used internally

abbreviation:str
abbreviation for the level achieved

coefficient:int
coefficient

domain:str
domain in which the acquisition is

domain_id:str
name:str
name (description) of the acquisition

name_id:str
pillar:str
pillar_id:str
pillar_prefix:str

**Comment by sosordinet** [comment]
Bonjour, allez voir dans les Pull request, j'y avais mis le code python pour les évaluations et acquisitions.

**Comment by jimsaye** [comment]
quand on sait ce que l'on fait c'est tout de suite plus facile. merci

**Comment by dathosim** [comment]
Je viens de faire une mise à jour du script python pour gérer les évaluations et les acquisitions de façon imbriquées ;-)
Reste a créer le Lovelace...

@sosordinet  : j'ai pas fait tout a fait comme toi..
j'ai un json imbriqué : pour chaque évaluations j'ai les acquisitions

Exemple pour la démo : 

```
    "evaluation": [
        {
            "date": "19/01/2022",
            "date_courte": "19/01",
            "eval": "ANGLAIS LV1",
            "desc": "Anglais \u00e9valuation T2 - Par mati\u00e8re",
            "coeff": 1,
            "palier": [
                "Cycle 4"
            ],
            "prof": "Mme BROWN J."
        },
        [
            {
                "acquisition_ordre": 1,
                "acquisition": "Comprendre des mots familiers et des expressions tr\u00e8s courantes",
                "acquisition_niveau": "Presque ma\u00eetris\u00e9",
                "acquisition_domaine": "\u00c9couter et comprendre",
                "acquisition_coeff": 1,
                "acquisition_palier": "LANGUES VIVANTES (\u00c9TRANG\u00c8RES OU R\u00c9GIONALES)",
                "acquisition_abreviation": "B"
            },
            {
                "acquisition_ordre": 2,
                "acquisition": "Se familiariser aux r\u00e9alit\u00e9s sonores de la langue, et s\u2019entrainer \u00e0 la m\u00e9morisation.",
                "acquisition_niveau": "Ma\u00eetrise satisfaisante",
                "acquisition_domaine": "\u00c9couter et comprendre",
                "acquisition_coeff": 1,
                "acquisition_palier": "LANGUES VIVANTES (\u00c9TRANG\u00c8RES OU R\u00c9GIONALES)",
                "acquisition_abreviation": "A"
            },
            {
                "acquisition_ordre": 3,
                "acquisition": "Comprendre des textes r\u00e9dig\u00e9s dans une langue courante et renvoyant \u00e0 un sujet connu",
                "acquisition_niveau": "Ma\u00eetrise satisfaisante",
                "acquisition_domaine": "Lire et comprendre",
                "acquisition_coeff": 1,
                "acquisition_palier": "LANGUES VIVANTES (\u00c9TRANG\u00c8RES OU R\u00c9GIONALES)",
                "acquisition_abreviation": "A"
            }
        ],
        {
            "date": "19/01/2022",
            "date_courte": "19/01",
            "eval": "ANGLAIS LV1",
            "desc": "Anglais \u00e9valuation T2 - Par mati\u00e8re",
            "coeff": 1,
            "palier": [
                "Cycle 4"
            ],
            "prof": "Mme BROWN J."
        },
        [
            {
                "acquisition_ordre": 1,
                "acquisition": "Comprendre des mots familiers et des expressions tr\u00e8s courantes",
                "acquisition_niveau": "Presque ma\u00eetris\u00e9",
                "acquisition_domaine": "\u00c9couter et comprendre",
                "acquisition_coeff": 1,
                "acquisition_palier": "LANGUES VIVANTES (\u00c9TRANG\u00c8RES OU R\u00c9GIONALES)",
                "acquisition_abreviation": "B"
            },
            {
                "acquisition_ordre": 2,
                "acquisition": "Se familiariser aux r\u00e9alit\u00e9s sonores de la langue, et s\u2019entrainer \u00e0 la m\u00e9morisation.",
                "acquisition_niveau": "Tr\u00e8s bonne ma\u00eetrise",
                "acquisition_domaine": "\u00c9couter et comprendre",
                "acquisition_coeff": 1,
                "acquisition_palier": "LANGUES VIVANTES (\u00c9TRANG\u00c8RES OU R\u00c9GIONALES)",
                "acquisition_abreviation": "A+"
            }
        ],

```

**Comment by sosordinet** [comment]
Super @dathosim,
C'est beaucoup mieux ainsi. 
Perso, je ne me sers pas des évaluations, par contre ça peut servir à ceux pour qui les enfants sont notés avec.
Si tu veux, j'ai fait aussi les moyennes.

![Screenshot_20220403_222454](https://user-images.githubusercontent.com/5613621/161447108-6c82d7ad-c7b5-42e5-a982-e40e16e73801.jpg)

Bravo pour ton boulot en tout cas.

**Comment by dathosim** [comment]
Les évaluations sont gérées - je clos ces échanges
