### ISSUE TITLE
heure de debut de cours non mis a jour

### ISSUE THREAD

**Issue by jimsaye** [dathosim/Pronote2Homeassistant#13]
Bonjour.
l'heure de début de cours n'est pas mis a jours si un cours est annulé en début de journée.
je ne reçois pas non plus de notification si un cours est annulé pour le lendemain alors que si c'est une cours qui est annulé le jour même oui.
est ce que cela peu être du à la même cause d'après vous ?

**Comment by dathosim** [comment]
Hello,
c'est compliqué de débugguer cela avec juste ces informations :(
Mais il faut savoir que les notifs en cas d'annulation sont gérés d'abord grâce aux sensors template : 
pronote_edt_demo_aujourdhui_cours_0_annulation 
pronote_edt_demo_aujourdhui_cours_1_annulation 
....

Ce sont des sensors qui doivent remonter le statut d'annulation du cours :
- Le sensor est à off : si le cours à bien lieu
- Et il est a "on" s'il a été annulé...

Tu peux donc commencer par regarder l'historique du sensor
pronote_edt_demo_aujourdhui_cours_0_annulation
grâce à l'outils de développement ou  le logbook 

Et voir s'il est passé de off à on à un moment
Et ensuite débuger l'automatisation qui gère ça 
Rappel : c'est une automatisation qui gère les envois de notification sur annulation de cours 

https://github.com/dathosim/Pronote2Homeassistant/blob/daa65a388b129d67ebf233eb72b4728418947e45/automation.yaml#L15

**Comment by jimsaye** [comment]
bien vu mon mes sensor est non disponible ça explique tout.
me reste plus à comprendre pourquoi

**Comment by dathosim** [comment]
Tu peux me copier la conf de ton sensor EDT du jour 
Et des sensor binary template qui gèrent les annulations 
Et je pourrais te dire si tu as un problème de syntaxe

**Comment by jimsaye** [comment]
sensor:

  - platform: rest
    name: pronote_edt_sandro_aujourdhui 
    scan_interval: 10
    json_attributes:
      - edt_aujourdhui
    value_template: >
        {% if value_json.edt_aujourdhui.0 is defined %}
            {{ value_json.edt_aujourdhui.0.date_heure }}
        {% else %}
            Pas cours
        {% endif %}
    resource: url_de_mon_ha.json
    
  - platform: rest
    name: pronote_edt_sandro_demain
    scan_interval: 10
    json_attributes:
      - edt_demain
    value_template: >
        {% if value_json.edt_demain.0 is defined %}
            {{ value_json.edt_demain.0.date_heure }}
        {% else %}
            Pas cours demain
        {% endif %}
    resource: url_de_mon_ha.json
    
  - platform: rest
    name: pronote_edt_sandro_prochainjour
    scan_interval: 10
    json_attributes:
      - edt_prochainjour
    value_template: >
        {% if value_json.edt_prochainjour.0 is defined %}
            {{ value_json.edt_prochainjour.0.date_heure }}
        {% else %}
            None
        {% endif %}
    resource: url_de_mon_ha.json
    
        
  - platform: rest
    name: pronote_note_sandro
    scan_interval: 10
    json_attributes:
      - note
    value_template: >
        {% if value_json.note.0 is defined %}
            {{ value_json.note.0.cours }} : {{ value_json.note.0.note_sur }} 
        {% else %}
            None
        {% endif %}
    resource: url_de_mon_ha.json


  - platform: rest
    name: pronote_devoir_sandro
    scan_interval: 10
    json_attributes:
      - devoir
    value_template: >
        {% if value_json.devoir.0 is defined %}
            {{ value_json.devoir.0.date }} / {{ value_json.devoir.0.title }} 
        {% else %}
            None
        {% endif %}
    resource: url_de_mon_ha.json


  - platform: rest
    name: pronote_absence_sandro
    scan_interval: 10
    json_attributes:
      - absence
    value_template: >
        {% if value_json.absence.0 is defined %}
            {{ value_json.absence.0.date_debut }} - {{ value_json.absence.0.nb_jours}}j - {{value_json.absence.0.nb_heures}}
        {% else %}
            None
        {% endif %}
    resource: url_de_mon_ha.json

  - platform: template
    sensors:
        pronote_edt_sandro_aujourdhui_cours_0_heure:
            friendly_name: "sandro / Début des cours"
            value_template: >-            
                {% if state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[0] is defined %}
                    {{state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[0]['heure']}}
                {% else %}
                    Pas cours
                {% endif %}                
                
        pronote_edt_sandro_demain_cours_0_heure:
            friendly_name: "sandro / Début des cours demain"
            value_template: >-            
                {% if state_attr('sensor.pronote_edt_sandro_demain', 'edt_demain')[0] is defined %}
                    {{state_attr('sensor.pronote_edt_sandro_demain', 'edt_demain')[0]['heure']}}
                {% else %}
                    Pas cours
                {% endif %}            
        pronote_edt_sandro_prochainjour_cours_0_heure:
            friendly_name: "sandro / Début des cours (J+1)"
            value_template: >-
                {% if state_attr('sensor.pronote_edt_sandro_prochainjour', 'edt_prochainjour')[0] is defined %}
                    {{state_attr('sensor.pronote_edt_sandro_prochainjour', 'edt_prochainjour')[0]['heure']}}  
                {% else %}
                    Pas cours
                {% endif %}        


binary_sensor:

  - platform: template
    sensors:
      pronote_edt_sandro_aujourdhui_cours_0_annulation:
        friendly_name: "Edt sandro Cours 0 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[0]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_1_annulation:
        friendly_name: "Edt sandro Cours 1 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[1]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_2_annulation:
        friendly_name: "Edt sandro Cours 2 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[2]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_3_annulation:
        friendly_name: "Edt sandro Cours 3 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[3]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_4_annulation:
        friendly_name: "Edt sandro Cours 4 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[4]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_5_annulation:
        friendly_name: "Edt sandro Cours 5 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[5]['annulation'] }}
      pronote_edt_sandro_aujourdhui_cours_6_annulation:
        friendly_name: "Edt sandro Cours 6 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[6]['annulation'] }}

  - platform: template
    sensors:
      pronote_edt_sandro_prochain_jour_cours_0_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 0 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[0]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_1_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 1 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[1]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_2_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 2 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[2]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_3_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 3 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[3]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_4_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 4 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[4]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_5_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 5 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[5]['annulation'] }}
      pronote_edt_sandro_prochain_jour_cours_6_annulation:
        friendly_name: "Edt sandro Prochain Jour Cours 6 annulation"
        value_template: >-
          {{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[6]['annulation'] }}

**Comment by jimsaye** [comment]
voici ma config

**Comment by jimsaye** [comment]
![2022-04-05 09_23_27-MessageCenterUI](https://user-images.githubusercontent.com/3946089/161700664-f08f1021-2850-4abe-9e48-c2db1c58af40.png)

et la ce sont mes entité indisponible

**Comment by dathosim** [comment]
Pas facile de voir si les binary sont bien déclarés ajouter les balises de code pour que le commentaire GitHub n'ajoute pas du formatage 
Mais à première vue ça me parait bon
Il faudrait regarder les logs au démarrage de Ha et voir à l'instanciation des sensors les erreurs remontées : ça peut donner une piste

**Comment by dathosim** [comment]
Sinon voir dans l'outils de développement / template 
Ce que renvoie la valeur 

{{ state_attr('sensor.pronote_edt_sandro_aujourdhui', 'edt_aujourdhui')[0]['annulation'] }}

**Comment by jimsaye** [comment]
2022-04-05 19:49:36 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: None has no element 3') while processing template 'Template("{{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[3]['annulation'] }}")' for attribute '_state' in entity 'binary_sensor.pronote_edt_sandro_prochain_jour_cours_3_annulation'
2022-04-05 19:49:36 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ state_attr('sensor.pronote_edt_sandro_prochain_jour', 'edt_prochainjour')[4]['annulation'] }}")

j'ai ça pour tout les sensor prochain jour

**Comment by jimsaye** [comment]
Salut, de retour car je n'ai pas eu le temps de m'attarder sur le sujet
voici une capture des logs si ça peu aider à comprendre. de mon coté ce n'est pas le cas  
![2022-04-07 22_21_26-Configuration – Home Assistant et 5 pages de plus - Personnel – Microsoft​ Edge](https://user-images.githubusercontent.com/3946089/162289529-7d6b95b8-be0f-464c-961e-a0df57835e0d.png)

**Comment by dathosim** [comment]
Essaye dans outils de développement comme je disais 2 ou 3 commentaire avant

Et n'oublie pas d'ajuster le chiffre car je vois l'erreur que pour le sensor 3 
Et ça se produit si y'a que 3 heurs de cours dans la journée
