### ISSUE TITLE
Format template obsolète avec nouvelle version HA

### ISSUE THREAD

**Issue by cob94440** [dathosim/Pronote2Homeassistant#15]
Bonjour,

Pourrais tu mettre à jour le fichier configuration à jour avec le nouveau format des templates?

Merci par avance

**Comment by Holborn13200** [comment]
Hello, quelqu'un aurais réaliser la modification pour prise en charge du nouveau format de template ? 
Merci.

**Comment by dathosim** [comment]
Mais quel est ce nouveau format des templates ?
Est-ce une mise à jour de HA 
ou le markdown que je donne en exemple qui ne fonctionne pas à cause d'une autre modif ?

**Comment by Holborn13200** [comment]
Visiblement c'est le template qui à changé, voici un exemple pour la 1ère :
```

1.       - type: entities
2.         entities:
3.           - sensor.pronote_edt_aujourdhui_cours_0_heure
4.           - sensor.pronote_edt_demain_cours_0_heure
5.           - sensor.pronote_edt_prochainjour_cours_0_heure
6.         title: Début des cours

```
Je suppose que le restant a aussi changé.
Il faut faire quelques adaptations, rien d'insurmontable pour moi, mais il serait intéressant de mettre à jour dans la repo.
Dans tous les cas, merci pour ton travail ! 🥇

**Comment by Holborn13200** [comment]
En réalité seul le premier bloque est à modifier (retirer "entity:") pour le reste tout est OK

**Comment by dathosim** [comment]
Hello @Holborn13200,
j'ai corrigé même s'il semble que les 2 formats soient encore acceptés
https://github.com/dathosim/Pronote2Homeassistant/commit/6ba9c54eca295252996c7f8c94d84c2c67cc5c01
