### ISSUE TITLE
Comment faire l'installation ?

### ISSUE THREAD

**Issue by kiki3529-0** [dathosim/Pronote2Homeassistant#16]
Bonjour
Je ne suis pas très bon
Comment installer sur ha?
Merci de votre aide et pour superbe travail très utile
Mickaël

**Comment by dathosim** [comment]
Bonjour, 
Avez-vous vu et essayé de l'installer avec la documentation présente en page d'accueil de ce repo sur Github ?
https://github.com/dathosim/Pronote2Homeassistant
En bas de cette page - sous liste des fichiers
