### ISSUE TITLE
Besoin d'aide pour la 1ere étape

### ISSUE THREAD

**Issue by Lepelot** [dathosim/Pronote2Homeassistant#2]
Bonjour, 
Comme beaucoup de grand parents, nous utilisons Pronote tous les mercredis et le reste de la semaine on s'amuse avec Home Assistant  :)

J'aimerai bien utiliser cette méthode pour remonter les informations (pour impressionner mes petits-enfants la semaine prochaine) mais je ne connais pas assez Pyton alors j'hésite a me lancer dans l'installation du script et du cronjob de peur de démolir mon installation HA. 

Serait-il possible de détailler un peu la procédure pour  installer ce script dans un dossier ; est-ce qu'il faut juste le copier dans le dossier avec Samba ? 

Pour la crontab, j'ai besoin d'aide, je ne vois pas comment il faut procéder? 

Pour le reste, je pense pouvoir me débrouiller. 

Merci d'avance et félicitations pour ce travail, je progresse tous les jours grâce à vous.

**Comment by djtale** [comment]
Bonsoir.

Pour crontab, il faut accéder en ssh à Home Assistant et taper :
crontab -e

**Comment by plouf34** [comment]
Bonjour quand cette étape est faite contrab -e, que faut il faire?

**Comment by dathosim** [comment]
@plouf34 : il faut donc lancer le script une première fois (le mettre en crontab sert à ce qu'il se lance de façon récurrente)
Vérifier dans le dossier www que le fichier json est généré 

Ensuite, il faut copier la configuration yaml dans le fichier de configuration de votre HA 
Ensuite relancer HA et vérifier par le developer tools de Ha que les sensors sont bien créés et remontent des valeurs 

Ok ?
