### ISSUE TITLE
2 élèves un en pronote compte parent l'autre en ent

### ISSUE THREAD

**Issue by cob94440** [dathosim/Pronote2Homeassistant#20]
Bonjour,

Comment avoir deux configurations ?
Doubler les pronote.py?

**Comment by dathosim** [comment]
Hello, non il suffit de passer un argument au script 
Et de détecter cet argument pour modifier la conf 
Ce qui permet de passer un argument différent selon l'enfant et ça génère 2 fichier json différents

Exemple de bout de code a ajouter : 

```
if len(sys.argv) > 1:
    if sys.argv[1] == "enfant1" :
        eleve_id="monenfant1" 
        prefix_url = "123456"
        username="PNOMENFANT1"
        password="mdpEnfant1"
    elif sys.argv[1] == "enfant2" :
        eleve_id="monenfant2" 
        prefix_url = "654321" 
        username="PNOMENFANT1"
        password="mdpEnfant2"
```
Mais une idée encore meilleur vient d'être proposé que je vais merger : mettre les conf dans un fichier de conf à part
Et de passer un argument pour lire ce fichier de conf passé

**Comment by dathosim** [comment]
Hello @cob94440, j'ai publié une modification du script pour la gestion de 2 comptes 
(externalisation de la configuration)
