### ISSUE TITLE
Cron impossible avec hassio

### ISSUE THREAD

**Issue by aardjoun** [dathosim/Pronote2Homeassistant#23]
Bonjour, j'ai bien le script qui fonctionne en manuel dans ha os avec l'addon ssh. Comme tout est containérisé le script cron ne semble pas ce lancer et je n'ai pas de remonté de donnés à moins de lancer manuellement le script. De plus en cas de maj de l'addon ou de redémarrage du rpi, les données ne sont pas persistantes et l'installation de python et pronotepy sont supprimés également. 
Est-ce qu'une version adaptée à ce type d'installation est possible ?
Merci

**Comment by PepereLoulou** [comment]
En ssh si tu tapes:
crontab -e

Est-ce que tu peux ajouter la cronjob ?

**Comment by dathosim** [comment]
pas de retour de @aardjoun : je ferme

**Comment by aardjoun** [comment]
Je n'avais pas vu le message. Je peux ajouter un cron avec crontab -e

**Comment by dathosim** [comment]
Il me semble que c'est plus compliqué que d'ajouter un crontab
Car tu perds python et pronotepy à chaque reboot 😫
Désolé je n'ai pas de solution
