### ISSUE TITLE
KeyError: 'ListEvaluations'

### ISSUE THREAD

**Issue by 3mb4rg0** [dathosim/Pronote2Homeassistant#24]
Bonsoir,

D'abord, merci pour le travail accompli et petite suggestion pour les nouveaux utilisateurs de votre code, pourriez-vous corriger le pronote.py en retirant les () à la ligne 274 => absences = client.current_period.absences (ça évitera de chercher les issues aux nouveaux)

Enfin, voici mon souci :
![image](https://user-images.githubusercontent.com/102162790/205798720-8ac331d4-84f7-4258-8ff9-87f2563d4d5b.png)

Je ne trouve personne qui en parle, sauriez-vous de quoi il s'agit ?

Bonne fin de nuit

**Comment by HermesHonshappo** [comment]
> pourriez-vous corriger le pronote.py en retirant les () à la ligne 274 => absences = client.current_period.absences (ça évitera de chercher les issues aux nouveaux)

Un grand merci à toi, car j'étais venu parcourir la liste des issues, étant tombé sur ce bug :-)

**Comment by dathosim** [comment]
corrigé
