### ISSUE TITLE
Note plus disponible

### ISSUE THREAD

**Issue by plouf34** [dathosim/Pronote2Homeassistant#25]
Bonjour, depuis le mois de novembre, je n'arrive plus a recuperer les notes et evaluations?
Tout le reste fonctionne parfaitement. Pour info, je n'ai pas de ENT (faisant partie de l'académie de Bordeaux).

**Comment by bartsec** [comment]
Bonjour @plouf34 , j'ai le même pb que toi depuis novembre. J'ai cherché mais ne parviens pas à corriger le pb.

Sur quoi tu héberges ton HA ?

**Comment by HermesHonshappo** [comment]
Hello folks

Est-ce que par hasard votre pronote n'aurait pas basculé sur "trimestre2"?  C'est le cas chez moi, et la dernière note affichée est celle du trimestre 1

Si c'est le cas, il y a apparemment un fix en cours d'étude chez bain3, qui est en charge de la librairie pronotepy
https://github.com/bain3/pronotepy/pull/197

**Comment by pelrol** [comment]
C'est corrigé ici : https://github.com/bain3/pronotepy/commit/54ab0dd87b9e178ac3383046e3bd35c1efa1527b
Il faut attendre que la version 2.9.0 sorte ou basculer sur la latest de pronotepy.

**Comment by pelrol** [comment]
La version 2.9.0 est bien sortie.

**Comment by dathosim** [comment]
les notes fonctionnent avec la version 2.9.0 ! je clos
