### ISSUE TITLE
Pronote pyscript : probleme client

### ISSUE THREAD

**Issue by yaazzz** [dathosim/Pronote2Homeassistant#26]
Bonjour, Merci pour cet addons.
J essais de le faire fonctionner sur HomeAssistant OS.
Lorsque je lance le script manuellement j´ai le message d erreur suivant:
```
[core-ssh ~]$ /usr/bin/python3 /config/python_scripts/pronote.py
Erreur de connexion via l'ENT avec le compte parent - vérifier les paramètres
Traceback (most recent call last):
  File "/config/python_scripts/pronote.py", line 94, in <module>
    if client.logged_in:
NameError: name 'client' is not defined
```
Avez vous une idée de ce que j´ai pu oublier?

**Comment by dathosim** [comment]
le message est (presque) clair : Erreur de connexion via l'ENT avec le compte parent - vérifier les paramètres

vous essayez de vous connecter via un ENT (pas en direct à pronote)
du coup il faut connaître le CAS (méthode d'authentification) utilisée dans votre collège ou lycée 
Et surtout vérifiez vos paramètre de connexion : login / pass

mais ça semble pas être un pb sur le code
