### ISSUE TITLE
Erreur récupération des absences

### ISSUE THREAD

**Issue by Fredzxda** [dathosim/Pronote2Homeassistant#27]
Le script retour l'erreur suivante :
Traceback (most recent call):
  File "/config/pyscript/pronote.py", line 277, in <module>
    absences = client.current_period.absences()
TypeError:  'list' object is not callable

**Comment by dathosim** [comment]
Je ne comprends pas d'où cela vient mais sur certaines installations (ou versions) il faut supprimer les parenthèses à la fin de cette ligne ()
Tu peux essayer et me faire un retour stp ? Et le préciser quelle version de la lib pronotepy tu as stp ?
Commande : pip list

**Comment by Fredzxda** [comment]
Je confirme que sans les () cela fonctionne avec pronotepy 2.8.0
Merci.

**Comment by pelrol** [comment]
C'est un changement qui a eu lieu dans [pronotepy 2.3.0](https://github.com/bain3/pronotepy/releases/tag/v2.3.0):
> change Period.absences() to a property by @bain3 in https://github.com/bain3/pronotepy/pull/94

Il faut conseiller de mettre à jour pronotepy dans la doc d'install.

**Comment by dathosim** [comment]
merci @pelrol 
je viens d'ajouter cela dans la doc ;-)

**Comment by dathosim** [comment]
@pelrol : je suis bien dans la dernière version de la lib pronotepy (la 2.9.0) 
et si je supprime les (). ça ne fonctionne pas chez moi 
(j'ai laissé les parenthèse dans la version sur Github - mais supprimé chez moi)

**Comment by dathosim** [comment]
Oh ! je viens de trouver ! 🎉
j'avais une version de la lib que j'avais copié dans le dossier python_script !
du coup, j'avais beau être a jour dans pip list il prenait la version locale 😜
je ferme cette issue aussi
