### ISSUE TITLE
configuration via agora6

### ISSUE THREAD

**Issue by hervefox** [dathosim/Pronote2Homeassistant#28]
bonjour, 

je profite de cette journée de grèves pour essayer de me faire des alertes en cas d'absence de professeurs ....

par contre je suis un peu perdu dans la configuration !
j'ai bien le compte élève ( en tant que parent je passe par france connect depuis la page https://cas.agora06.fr/ )
du coup j'ai pris l'accès de mon enfant.
il se connecte également sur agora06 puis son pronote est sur ce lien : http://notes.clg-paul-langevin.ac-nice.fr/pronote/eleve.html?identifiant=xxxxx

quelqu'un a réussi à paramétrer avec un accès autre que index-education.net ?

on peut se logger via le QRcode sinon ?

merci de votre aide 

PS: en fouillant un peut pronotepy connais bien agora06 , il me reste à le faire prendre en compte dans le python

**Comment by dathosim** [comment]
la dernière version de la lib pronotepy inclue agora06 : je l'ai ajouté à mon script
du coup, je ferme
