### ISSUE TITLE
Demande d'ajout ENT77

### ISSUE THREAD

**Issue by yodn** [dathosim/Pronote2Homeassistant#31]
Bonjour, 

Pouvez-vous ajouter ent77 svp.
Merci

1. Dans le fichier ent.py :

> section """Open ENT NG""" :
```
ent_seine_et_marne = partial(_open_ent_ng, url="https://ent77.seine-et-marne.fr/auth/login")
```
2. Dans le fichier __init__.py :
```
ent_seine_et_marne,
```
3. Dans le fichier pronote.py :

```
from pronotepy.ent import ent_seine_et_marne
```
...
```
elif ent == "ent_seine_et_marne":
        ent = ent_seine_et_marne
```

**Comment by dathosim** [comment]
Hello @yodn
personnelement sur ce repo je ne peux faire l'ajout que des lignes dans le fichiers pronote.py (le point 3) 
Pour les point 1 et 2 il faut faire une demande ici 
https://github.com/bain3/pronotepy/issues

Et tant que les points 1 et 2 ne sont pas fait je ne peux pas le faire dans le script

**Comment by dathosim** [comment]
je te propose de refaire la demande dès que @bain3 a fait l'ajout stp ?

**Comment by bain3** [comment]
Cet ENT est implementé comme [`pronotepy.ent.ent77`](https://pronotepy.readthedocs.io/en/stable/api/ent.html#pronotepy.ent.ent77) depuis `v2.4.0`.
