### ISSUE TITLE
Ajout ent77

### ISSUE THREAD

**Issue by yodn** [dathosim/Pronote2Homeassistant#32]
Bonjour,

Pouvez-vous ajouter ent77 svp.
Déjà disponible dans [https://github.com/bain3/pronotepy](https://github.com/bain3/pronotepy)
Merci

Dans le fichier pronote.py :

```
from pronotepy.ent import ent77

```
...

```
elif ent == "ent77":
        ent = ent77
```

**Comment by pelrol** [comment]
Ca devrait marcher avec cette pull request : https://github.com/dathosim/Pronote2Homeassistant/pull/33

**Comment by yodn** [comment]
Bonjour @pelrol,
Merci pour les modification mais je viens de tester, il faut comme même la partie ci-dessous sinon il ne se connecter pas a ent

```
elif ent == "ent77":
        ent = ent77
```

**Comment by pelrol** [comment]
Justement, normalement la modification de la pull request permet de charger n'importe quelle ent en dynamique.
Tu as quelle erreur ?

**Comment by yodn** [comment]
```
Exception has occurred: NameError
name 'client' is not defined
  File "C:\HA\Pronote\pronote.py", line 89, in <module>
    if client.logged_in:
NameError: name 'client' is not defined
```

`Erreur de connexion à Pronote (sans ENT) avec le compte parent - vérifier les paramètres`

**Comment by pelrol** [comment]
Je ne sais pas trop ce qui s'est passé avec git, le souci vient d'un conflit sur la pull request : https://github.com/dathosim/Pronote2Homeassistant/pull/33/conflicts

Il faut ajouter la ligne suivante:
`from pronotepy.ent import *`

**Comment by dathosim** [comment]
Je viens de merge la modification pour importer tous les ENT d'un coup

**Comment by yodn** [comment]
cela fonctionne 👍 
Merci
