### ISSUE TITLE
Circonvernir CAS (

### ISSUE THREAD

**Issue by vingerha** [dathosim/Pronote2Homeassistant#4]
J'ai installé le tout et pour 'demo'  ça marche bien....alors pas vraiment un soucis avec votre sollution mais.... j'ai des soucis avec un CAS avant (agora06). Est-ce que vous êtes intéssés de l'intégrer ou est-ce que je doit utiliser une alternative avant (p.e. [v0ltis](https://github.com/v0ltis)
/[Pronote-APIpy](https://github.com/v0ltis/Pronote-APIpy)

**Comment by vingerha** [comment]
Découvert qu'il y a des solutions ENT de pronotepy......

**Comment by vingerha** [comment]
Découvert qu'il y a des solutions ENT de pronotepy......

**Comment by dathosim** [comment]
Bien vu !
En effet, pronotepy permet aussi de se connecter via les CAS (comme l'ENT) de certaines académies 
Mais pas tous les CAS et donc pas toutes les académies 
Mais ça me fait penser que je vais mettre quelques ligne dans la doc et dans le code pour laisser le choix entre pronote ou CAS

**Comment by vingerha** [comment]
J'ai reussi d'ajouter CAS agora06 de la base d'un autre CAS et une intégration pronote java. Clairement, le gouvernement a demandé quelquns de quitter leur travail cause acces irreglemantaire...rigolo...au lieu de creer une systeme qui est solide... lol
