### ISSUE TITLE
Erreur de connexion pronote

### ISSUE THREAD

**Issue by aardjoun** [dathosim/Pronote2Homeassistant#40]
En testant ce soir la connexion a pronote j'ai une erreur :

```
$ /usr/bin/python3.7 /home/pirate/Pronote2Homeassistant/pronote.py
[_Communication.initialise] Failed to parse html, retrying...
[_Communication.initialise] Failed to parse html, retrying...
[_Communication.initialise] Failed to parse html, retrying...
Erreur de connexion à Pronote (sans ENT) avec le compte parent - vérifier les paramètres
Traceback (most recent call last):
  File "/home/pirate/Pronote2Homeassistant/pronote.py", line 83, in <module>
    if client.logged_in:
NameError: name 'client' is not defined
```

J'ai vérifié les identifiants en me connectant directement sur le site.

**Comment by yodn** [comment]
meme erreur


[_Communication.initialise] Failed to parse html, retrying...
[_Communication.initialise] Failed to parse html, retrying...
[_Communication.initialise] Failed to parse html, retrying...
Erreur de connexion via l'ENT avec le compte parent - vérifier les paramètres

Une exception s'est produite : NameError
name 'client' is not defined
  File "W:\Pronote\pronote.py", line 83, in <module>
    if client.logged_in:
NameError: name 'client' is not defined

**Comment by yodn** [comment]
Ca fonctionne, il faut mettre le dossier pronotepy à jour
[https://github.com/bain3/pronotepy](url)

**Comment by aardjoun** [comment]
Pour ceux qui ont installé pronotepy avec pip il faut passer par la commande suivante pour la mise à jour : 

```pip install -U git+https://github.com/bain3/pronotepy```
