### ISSUE TITLE
HACS ?

### ISSUE THREAD

**Issue by saniho** [dathosim/Pronote2Homeassistant#5]
Hello, très bonne idée cette intégration, est-il prevu une version compatible HACS ?

**Comment by dathosim** [comment]
Merci ! Pour l'instant je n'ai pas prévu une version HACS - en fait cela voudrait dire développer une véritable integration - pour l'instant ce n'est qu'un script et de la configuration de sensor ☺️
Mais si tu as ce talent n'hésite pas !

**Comment by saniho** [comment]
Je peux en effet filer un coup de main pour creer ce projet( j'ai 2/3 projets HA : https://github.com/saniho/ )
...après il faudrait réfléchir à l'objectif final... quoi voir sur ha ? emploi du temps, note etc... quel sensor...Si tu as des idées.

**Comment by dathosim** [comment]
Merci pour ta proposition ! 
Je suis preneur pour l'init du projet !
En fait, ça serait refaire ce qui a été fait mais dans une véritable intégration custom 
Toute la matière est la!
Ça serait surtout pour faciliter l'installation - et la configuration avec des écrans UI qui te demande ton prefix, ton login et mdp pronote (et bonus CAS ou pas)
Dans un premier temps on peut garder la logique de 3 sensors qui ramène des json 
Et on pourra fournir le Lovelace pour afficher les infos 
Qu'en penses tu ?
Merci encore

**Comment by vingerha** [comment]
Pour ne pas faire des choses duplicés..... je suis en train de finir une première version intégrer pronotepy vers HA via MQTT....je sais...c'est pas la même mais juste pour info. Raisons pour choisir mqtt: REST ne marche pas vraiment stable chez moi et je voudrais avoir les données dans un db avant de les exposer.... j'ai pris gazpar2mqtt comme example.

**Comment by saniho** [comment]
Par contre, j'ai vu un dev qui a été obligé d'arreter son appli utilisant pronotes, il serait peut-etre bon de demander l'accord à l'editeur : https://www.index-education.com/fr/assistance-email.php

**Comment by vingerha** [comment]
Oui, je l'ai vu aussi mais je ne comprends rien de leur raisssonnement. Ponotepy utilise des fonctionalités librement ouvert pour la publique, rien de type 'hacker'. Si le gouvernement ne peut pas créer des outils sécu, c'est pas a les developpeurs d'árrêter leurs travail.... mais d'ameliorer les outils et payer les devs qui ont découvert les défaut. ...comme fait par Google/Facebook/etc. En réalité, si on publie une livre sur ce sujet ou une article internet globale...tout le monde peut le faire soit même. 
Mais...de l'autre part, qui a du temps pour se battre avec un gouvernement?
Pour ma part, je re-utilise "pronotepy" pour extraire les données et je construis une autre méthode pour leurs presentation..... Dans se cas, je ne fait rien du tout vers un gouvernemenet car ils sont de nature paresseus (prendre une route facile) et sans beaucoup d'attention il vont dir 'non' ... alors, on vera :)

Dans le même sujet, vous avez crée un outil d'extraire des données 'linky' d'edf ... avez vous demandé un permis d'edf ?

**Comment by dathosim** [comment]
> Par contre, j'ai vu un dev qui a été obligé d'arreter son appli utilisant pronotes, il serait peut-etre bon de demander l'accord à l'editeur : https://www.index-education.com/fr/assistance-email.php

Pour le dev qui a été obligé d'arrêter du doit vouloir parler de ça ? 
https://github.com/Litarvan/pronote-api

Et pour le formulaire : il est fait pour les clients de Pronote - c'est dire les établissement ou collectivités...du coup on peut pas trop les contacter via ça...

**Comment by vingerha** [comment]
Je viens de lui adresser un email...on vera. J'ai aussi vu q'il existes déjà 2 forks de son travail qui sont encore dispo.
Et...je ne vais pas contacter IndexEdu car je ne suis pas concerné ...plutôt 'pronotepy' comme collecteur des données.

**Comment by vingerha** [comment]
Ma première version: https://github.com/vingerha/pronote2mqtt
Vous avez besoins de MQTT et tout commentaire apprécié
(pas de réponse de Litarvan pour l'instant)

**Comment by Laxttt** [comment]
Qui a des tools termux pour faire du phishing pronote ?
