### ISSUE TITLE
Discussion sur l'API 

### ISSUE THREAD

**Issue by ghost** [dathosim/Pronote2Homeassistant#6]
Bonjour @dathosim, ceci n'est pas une issue mais est-ce que je peux vous contacter pour de l'aide avec l'API Pronote de bain3 ?

**Comment by dathosim** [comment]
Oui! Je suis joignable ici...
Comment puis-je vous aider ?

**Comment by dathosim** [comment]
Oui! Je suis joignable ici...
Comment puis-je vous aider ?

**Comment by ghost** [comment]
Je souhaite extraire les infos de l'utilisateur avec pronotepy.dataClasses.Student sauf que je suis très paumé en terme d'API et je ne trouve pas mon problème. Je ne connais pas la commande qui permet d'utiliser ces attributs.
![image](https://user-images.githubusercontent.com/89639215/153268694-84ef21e7-07c8-475b-aa18-e73cd43e1db5.png)
![image](https://user-images.githubusercontent.com/89639215/153268926-47723712-d9e7-4c84-82bf-ebd624adc64e.png)

**Comment by dathosim** [comment]
Alors, je n'ai pas exploré toute la lib pronotepy et je suis pas un pur dev python donc je ne suis pas sûr de pouvoir t'aider...
Mais déjà je vois une erreur dans ton code qui est souligné : student et non Student avec la majuscule...
Aussi je te conseille si ce n'est pas déjà le cas d'utiliser l'éditeur Visual Studio Code : ça permet de faire de l'autocompletion 
Voilà

**Comment by vingerha** [comment]
My 2 cents.... 
En fait... sans savoir la source c'est difficile de tenter comment extraire car aussi pronotepy est une adaptation et ne couvre pas tous les fonctions.
Moi, j'ai essaié pendant des heures pour les Student / Identity sans progrès et finalement, j'ai décidé que je connait mes enfants mieux que pronote...abandonné. 
Ajoutant des nouveautés (pour moi) car l'un de mes enfants a des 'notes' et l'autre (plus jeune) que des 'evaluations'. 
Pour soutenir mes demandes, je suis en train de mettre 'beaucoup' dans un sqlite-db pour une publication par mqtt. Le REST ne marche pas tous le temps (pour moi)... ,mais je vais garder l'esprit de dathosim dedans et j 'espère de finir dans quelques semaines.

**Comment by dathosim** [comment]
En effet, j'ai regardé aussi...et il manque des méthodes dans le fichier clients.py de la Pronotepy 
Il n'y a rien d'implémenter pour récupérer les "identity"

**Comment by vingerha** [comment]
je vais voir avec bainf s'il veut partager comment il a obtenu ces infos.

**Comment by ghost** [comment]
Après une conversation avec bain3, `pronotepy.dataClasses.Identity` ne marche que pour les comptes Vie Scolaires.
J'utilise `client.parametres_utilisateur` pour récupérer mon nom complet, ma classe et mon établissement.

![image](https://user-images.githubusercontent.com/89639215/153700968-f709a378-68ac-4137-baa4-b385d4843680.png)

Lorsque j'ouvre le fichier json, je me retrouve avec 5 fois les memes infos. 

![image](https://user-images.githubusercontent.com/89639215/153700986-96e27d8e-0395-4c52-84ec-776ef87ca23a.png)


Comment je fais pour qu'il affiche une seule fois ?

**Comment by vingerha** [comment]
Je suis en route, retour des vacances et je vais voir demain .... et merçi pour avoir contacté le czech :)

**Comment by ghost** [comment]
bain3 propose d'utiliser `client.info` pour récupérer les informations : 

- établissement `client.info.establishment`
- classe `client.info.class_name`
- nom complet `client.info.name`
- les classes où l'eleve est délégué `client.info.delegue`

Après si vous êtes aventureux, vous pouvez utiliser `client.parametres_utilisateur` qui contient + d'infos (proposé par drawbot qui a développé un bot Discord avec l'API de bain3).

**Comment by ghost** [comment]
dathosim, pouvez-vous regarder mon problème en haut ? Mon script a imprimé 5 fois les memes infos dans le fichier .json, désolé je ne suis pas familier avec JSON.

**Comment by vingerha** [comment]
essaie de ne pas itérer...enlever le for-loop

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/89639215/153717458-b21765b8-5d89-4b43-8ac5-78b9a9b32a2a.png)

Merci beaucoup, ça a marché !

**Comment by ghost** [comment]
Bonjour, désolé de vous déranger encore une fois.
Est-ce que l'un d'entre vous a pu programmer quelque chose permettant de montrer l'évolution d'une moyenne (par exemple, moyenne générale ou d'une matière) au fur des notes ?
Cordialement, jusdecitron.

**Comment by vingerha** [comment]
Il y a déjà beaucoup dans les données, svp de me preciser un peu plus ce que vous chercher.
Moi, je suis ent train de créer un Interface pronotepy>mqtt>homeassistant. 
Dans cela je couvre moyennes (averages). On peut iterer client.periods.averages, 
ça donne (copié/collé):
self.student: str = self._resolver(Util.grade_parse, "moyEleve", "V")
self.out_of: str = self._resolver(Util.grade_parse, "baremeMoyEleve", "V")
self.default_out_of: str = self._resolver(Util.grade_parse, "baremeMoyEleveParDefault", "V", default="")
self.class_average: str = self._resolver(Util.grade_parse, "moyClasse", "V")
self.min: str = self._resolver(Util.grade_parse, "moyMin", "V")
self.max: str = self._resolver(Util.grade_parse, "moyMax", "V")

**Comment by 889laurent** [comment]
bonsoir a tous, une petite question pour la gestion des cas. J'utilise le cas AGORA 06 qui est dans pronotepy. Comment le rajouter. J'ai fait 
```
import pronotepy
from pronotepy.ent import cas_agora06_educonnect
eleve="*****" #nom de votre enfant - ne sert que pour le nom du fichier json
prefix_url = "notes.clg-saint-blaise.ac-nice.fr/" # sert au prefix de l'url https://PREFIX.index-education.net/pronote/
username="***" #utlisateur pronote  - a remplacer par le nom d'utilisateur pronote de l'élève
password="***" # mot de passe pronote - a remplacer par le mot de passe du compte de l'élève
ent="cas_agora06_educonnect"

index_note=0 
limit_note=11 #nombre max de note à afficher + 1 
longmax_devoir = 125 #nombre de caractère max dans la description des devoirs

#Connection à Pronote 
client = pronotepy.Client('http://'+prefix_url+'pronote/eleve.html?login=true', username, password, ent)
```


mais message erreur

**Comment by vingerha** [comment]
Je pense que vous avez reçu un email sur les changements.... alors le CAS à aussi changé, il faut adapter ENT.py avec 'selection=ATS-NICE'
```.
... 
     https://cas.agora06.fr/login?selection=ATS-NICE
```

**Comment by ghost** [comment]
Bonjour à vous deux et ceux qui passent par cette issue,
Je vous propose qu'on fasse un canal Slack pour parler plus de l'API de bain3.
Je pense pas qu'une issue est un endroit approprié pour une discussion :) 

Lien d'invitation au canal Slack :
https://join.slack.com/t/pronoteapi-discussion/shared_invite/zt-19bzgnq8w-r6pcJ_RY8vB~K6Kf8XL6rA
