### ISSUE TITLE
Colorisations et autre

### ISSUE THREAD

**Issue by vingerha** [dathosim/Pronote2Homeassistant#7]
Bonjour, n'importe quoi je fais, j'ai que des couleurs blanc ou jaunes comme 'background' dans les cards...svd, jaune si les devoirs sont faits. Est-ce que je manque un e parti de l'installation?

**Comment by vingerha** [comment]
En plus, je voudrais savoir si vous êtes intéressé de revoir mon taff pronotepy>mqtt>ha en 'docker' image avant de le publier

**Comment by vingerha** [comment]
et... j'ai fini la premiè3re version de l'intégration avec mqtt...est ce que vous êtes intéressé de le tester? 
Ça depend bien sûre si vous utiliser déjà mqtt avec has. Bainf m'a offert de l'aussi tester sur le scripting ( je ne suis pas développeur de nature)

**Comment by dathosim** [comment]
Pour la colorisation sur le lovelace des devoirs, il doit y avoir une erreur dans le bloc intégré - est-ce que la couleur et la mise en forme fonctionne pour les autres blocs ? 
Screenshot svp ?

Pour le mqtt : je veux bien tester si e trouvé le temps - ça le fera progresser car je ne connais pas bien 😜

**Comment by vingerha** [comment]
Ne t'inquiète pas pour MQTT, c'était un essai pour moi, aussi pour apprendre comment creer le flow dev>git-release>docker-release en mode 'stable' ... et c'est bon pour le moment. 
Lovelace marche maintenant, de quelle erreur tu parle? La seule chose avec mes cartes c'est qu'ils souvent lent a réagir sur les css, j'ai 4 cartes dans mon dashboard, les données sont visible directement mais l'application des colorisations/etc. de temps en temps après 4 sec.

**Comment by dathosim** [comment]
Pour MQTT : ok ! 
Pour l'erreur : je parle de l'erreur de colorisation que tu signales dans le premier commentaire de l'issue ;-) 
Mais peut être que tu ne l'as plus... et en effet, au chargement on voit rapidement apparaître des mark en jaune (la css de base de HA) et ensuite la CSS custom chargé dans le markdown prends le dessus
pour moi ça prend pas 4 sec ! ça prends max une seconde et c'est souvent invisible

**Comment by vingerha** [comment]
4...voir 8 il y a 10 min....je pense que c'est mon ordi...

**Comment by dathosim** [comment]
Je clos le ticket si tu veux bien 😉
